"""SQLite persistence for trades, signals, snapshots, and PDT tracking.

WHAT THIS MODULE DOES:
    Provides a thin, safe wrapper around SQLite for all data that needs
    to survive bot restarts: trade records, day-trade counts, daily
    equity snapshots, signal logs, options trades, and scanner results.

WHY IT EXISTS:
    The trading bot needs persistent storage for:
    1. Trade history — to calculate P&L, win rate, and other metrics.
    2. Day-trade records — to enforce the PDT rule across restarts.
    3. Daily snapshots — to compute drawdown and equity curves.
    4. Signal logs — to audit which signals were generated vs. acted on.
    5. Scanner results — to review what the screener found each morning.

    SQLite was chosen because it's file-based (no server to run), comes
    built into Python's standard library, and handles the modest write
    volumes of a single-account trading bot perfectly.

KEY DESIGN DECISIONS:
    - SQL injection prevention: all column names are validated against a
      regex before being interpolated into SQL.  Values are always passed
      as parameterized queries (the `?` placeholders), which SQLite's
      driver handles safely.
    - The @contextmanager pattern ensures database connections are always
      properly committed and closed, even if an error occurs.
    - Generic _insert, _update, _upsert methods use **kwargs to accept
      arbitrary columns, making it easy to add new fields without changing
      the method signatures.
    - The database file is stored at `<project_root>/data/ai_trade.db`.
      The directory is created automatically if it doesn't exist.

SCHEMA OVERVIEW:
    - trades:           Stock trade records (open, closed, pending).
    - day_trades:       PDT tracking records for the rolling 5-day window.
    - daily_snapshots:  End-of-day equity/cash snapshots for performance charts.
    - signals:          Log of every signal generated by strategies.
    - options_trades:   Options-specific trade records with Greeks and strikes.
    - scanner_results:  Pre-market screener output for each day.
"""

from __future__ import annotations

import re
import sqlite3
import time

# PYTHON PATTERN — @contextmanager:
# The `contextmanager` decorator lets you write a generator function that
# can be used with Python's `with` statement.  Code before the `yield`
# runs on entry, code after `yield` runs on exit (even if an error occurs).
# This is the standard pattern for resource management in Python (like
# try-with-resources in Java or using blocks in C#).
from contextlib import contextmanager
from pathlib import Path

from ai_trade._version import __version__
from ai_trade.monitoring.logger import get_logger

_db_log = get_logger(__name__)

# Max retries for database operations that fail due to locking
_DB_MAX_RETRIES = 3
_DB_RETRY_DELAY = 0.5  # seconds

# Resolve the database directory: 3 levels up from this file's location
# (monitoring/ → ai_trade/ → src/ → project root), then into data/.
# Path.resolve() converts to an absolute path, and .parents[N] walks up N directories.
_DB_DIR = Path(__file__).resolve().parents[3] / "data"
_DB_PATH = _DB_DIR / "ai_trade.db"

# Regex for validating SQL column names.
# Only allows: starts with a letter or underscore, followed by
# letters, digits, or underscores.  This prevents SQL injection through
# column names (e.g., someone passing "name; DROP TABLE trades" as a column).
_COL_RE = re.compile(r"^[a-z_][a-z0-9_]*$", re.IGNORECASE)

# The complete database schema as a SQL script.
# "CREATE TABLE IF NOT EXISTS" is idempotent — safe to run every time
# the bot starts.  It only creates tables that don't already exist.
_SCHEMA = """
CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    side            TEXT NOT NULL,
    shares          REAL NOT NULL,
    entry_price     REAL,
    entry_time      TEXT,
    exit_price      REAL,
    exit_time       TEXT,
    stop_loss       REAL,
    take_profit     REAL,
    hold_type       TEXT NOT NULL,
    pnl             REAL,
    pnl_pct         REAL,
    status          TEXT NOT NULL DEFAULT 'pending',
    buy_order_id    TEXT,
    sell_order_id   TEXT,
    bot_version     TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS day_trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT NOT NULL,
    trade_date      TEXT NOT NULL,
    buy_order_id    TEXT,
    sell_order_id   TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS daily_snapshots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT NOT NULL UNIQUE,
    equity          REAL NOT NULL,
    cash            REAL NOT NULL,
    open_positions  INTEGER NOT NULL DEFAULT 0,
    day_trades_used INTEGER NOT NULL DEFAULT 0,
    realized_pnl    REAL NOT NULL DEFAULT 0,
    unrealized_pnl  REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT NOT NULL DEFAULT (datetime('now')),
    symbol          TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    conviction      REAL NOT NULL,
    hold_type       TEXT NOT NULL,
    direction       TEXT NOT NULL DEFAULT 'long',
    action_taken    TEXT
);

CREATE TABLE IF NOT EXISTS options_trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    underlying      TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    legs            TEXT NOT NULL,
    qty             INTEGER NOT NULL DEFAULT 1,
    entry_credit    REAL,
    entry_debit     REAL,
    max_loss        REAL,
    max_profit      REAL,
    expiration      TEXT,
    strikes         TEXT,
    net_delta       REAL,
    net_theta       REAL,
    pnl             REAL,
    status          TEXT NOT NULL DEFAULT 'open',
    order_id        TEXT,
    bot_version     TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    closed_at       TEXT
);

CREATE TABLE IF NOT EXISTS scanner_results (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    price           REAL,
    gap_pct         REAL,
    relative_volume REAL,
    adr_pct         REAL,
    score           REAL,
    selected        INTEGER NOT NULL DEFAULT 0
);

-- Performance indexes for frequent queries
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_created_at ON trades(created_at);
CREATE INDEX IF NOT EXISTS idx_options_trades_status ON options_trades(status);
CREATE INDEX IF NOT EXISTS idx_options_trades_underlying ON options_trades(underlying);
CREATE INDEX IF NOT EXISTS idx_daily_snapshots_date ON daily_snapshots(date);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp);
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_day_trades_date ON day_trades(trade_date);
"""


def _validate_columns(columns: list[str]) -> None:
    """Ensure column names are safe identifiers (prevent SQL injection).

    Since column names can't use parameterized queries (the `?` placeholder
    only works for VALUES), we validate them against a strict regex.
    Any column name containing characters outside [a-zA-Z0-9_] is rejected.

    Raises:
        ValueError: If any column name doesn't match the safe pattern.
    """
    for col in columns:
        if not _COL_RE.match(col):
            raise ValueError(f"Invalid column name: {col!r}")


class Database:
    """Thin wrapper around SQLite for the trading system.

    All public methods handle their own connection lifecycle via the
    _conn() context manager — no connection pooling or threading concerns.

    PYTHON PATTERN — **kwargs (keyword arguments):
        Many methods here accept **kwargs, which collects all named
        arguments into a dictionary.  For example:
            db.insert_trade(symbol="AAPL", shares=100, status="open")
        Inside the method, kwargs = {"symbol": "AAPL", "shares": 100, "status": "open"}.
        This makes the API flexible — you can pass any combination of
        columns without defining separate parameters for each one.
    """

    def __init__(self, db_path: str | Path | None = None):
        """Initialize the database, creating the file and tables if needed.

        Args:
            db_path: Optional path to the SQLite database file.
                     If None, uses the default path at <project>/data/ai_trade.db.
        """
        self._path = Path(db_path) if db_path else _DB_PATH
        # .mkdir(parents=True, exist_ok=True) creates the directory AND
        # all parent directories if they don't exist.  exist_ok=True means
        # it won't raise an error if the directory already exists.
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _init_schema(self) -> None:
        """Run the schema creation script.

        executescript() runs multiple SQL statements separated by semicolons.
        Since we use IF NOT EXISTS, this is safe to run on every startup.
        If the DB is corrupted, logs the error and re-creates it.
        """
        try:
            with self._conn() as conn:
                conn.executescript(_SCHEMA)
        except sqlite3.DatabaseError as e:
            _db_log.error("schema_init_failed", error=str(e), path=str(self._path))
            # If the database file is corrupted, back it up and start fresh
            if "malformed" in str(e).lower() or "corrupt" in str(e).lower():
                backup = self._path.with_suffix(".db.corrupted")
                _db_log.warning("database_corrupted_backing_up", backup=str(backup))
                try:
                    self._path.rename(backup)
                except OSError:
                    pass
                with self._conn() as conn:
                    conn.executescript(_SCHEMA)
            else:
                raise
        self._migrate()

    def _migrate(self) -> None:
        """Apply incremental schema migrations for existing databases."""
        migrations = [
            ("trades", "bot_version", "ALTER TABLE trades ADD COLUMN bot_version TEXT"),
            ("options_trades", "bot_version", "ALTER TABLE options_trades ADD COLUMN bot_version TEXT"),
        ]
        try:
            with self._conn() as conn:
                for table, column, sql in migrations:
                    cursor = conn.execute(f"PRAGMA table_info({table})")
                    columns = [row[1] for row in cursor.fetchall()]
                    if column not in columns:
                        conn.execute(sql)
                        _db_log.info("schema_migrated", table=table, column=column)
        except Exception as e:
            _db_log.warning("migration_failed", error=str(e))

    @contextmanager
    def _conn(self):
        """Context manager that provides a database connection.

        Handles SQLite-specific failure modes:
        - OperationalError from database locks (retries with backoff)
        - DiskFull / PermissionError (logged with actionable message)

        sqlite3.Row is set as the row_factory so query results can be
        accessed by column name (e.g., row["symbol"]) in addition to
        index (e.g., row[0]).
        """
        conn = sqlite3.connect(str(self._path), timeout=10)
        # Row factory makes rows behave like dictionaries — much more
        # readable than positional indexing.
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()  # Auto-commit on successful exit
        except sqlite3.OperationalError as e:
            error_msg = str(e).lower()
            if "locked" in error_msg or "busy" in error_msg:
                _db_log.warning("database_locked", error=str(e), path=str(self._path))
            elif "disk" in error_msg or "full" in error_msg or "readonly" in error_msg:
                _db_log.error("database_disk_error", error=str(e), path=str(self._path))
            raise
        finally:
            conn.close()   # Always close, even if an error occurred

    def _retry_on_lock(self, operation, *args, **kwargs):
        """Retry a database operation up to _DB_MAX_RETRIES if the DB is locked.

        SQLite uses file-level locking.  If another thread or process holds
        the lock (e.g. the position sync and a trade insert happen
        simultaneously), the operation will raise OperationalError.  This
        method retries with a short delay to handle transient locks.
        """
        for attempt in range(1, _DB_MAX_RETRIES + 1):
            try:
                return operation(*args, **kwargs)
            except sqlite3.OperationalError as e:
                if ("locked" in str(e).lower() or "busy" in str(e).lower()) and attempt < _DB_MAX_RETRIES:
                    _db_log.warning("db_locked_retrying", attempt=attempt, error=str(e))
                    time.sleep(_DB_RETRY_DELAY * attempt)
                else:
                    raise

    def _insert(self, table: str, **kwargs) -> int:
        """Generic safe insert — validates column names, uses parameterized values.

        Retries on database lock errors.  Column names are validated, and
        values use `?` placeholders (parameterized queries) to prevent
        SQL injection.

        Returns:
            The auto-generated row ID of the inserted record.
        """
        def _do_insert():
            cols = list(kwargs.keys())
            _validate_columns(cols)
            col_str = ", ".join(cols)
            placeholders = ", ".join(["?"] * len(cols))
            with self._conn() as conn:
                cur = conn.execute(
                    f"INSERT INTO {table} ({col_str}) VALUES ({placeholders})",
                    list(kwargs.values()),
                )
                return cur.lastrowid or 0
        return self._retry_on_lock(_do_insert)

    def _upsert(self, table: str, **kwargs) -> None:
        """Generic safe INSERT OR REPLACE — retries on lock.

        If a row with the same PRIMARY KEY or UNIQUE constraint already
        exists, it's replaced.  Otherwise, a new row is inserted.
        """
        def _do_upsert():
            cols = list(kwargs.keys())
            _validate_columns(cols)
            col_str = ", ".join(cols)
            placeholders = ", ".join(["?"] * len(cols))
            with self._conn() as conn:
                conn.execute(
                    f"INSERT OR REPLACE INTO {table} ({col_str}) VALUES ({placeholders})",
                    list(kwargs.values()),
                )
        self._retry_on_lock(_do_upsert)

    def _update(self, table: str, row_id: int, **kwargs) -> None:
        """Generic safe update by id — validates column names.

        Builds an UPDATE statement dynamically.  Only updates the columns
        specified in kwargs.

        Example:
            self._update("trades", 42, status="closed", exit_price=51.20)
            → UPDATE trades SET status = ?, exit_price = ? WHERE id = ?
              with parameters ["closed", 51.20, 42]

        PYTHON PATTERN — [*iterable, extra]:
            The `[*kwargs.values(), row_id]` syntax unpacks the dict values
            into a list and appends row_id at the end.  The `*` operator
            inside a list literal "spreads" the iterable's elements.
        """
        def _do_update():
            cols = list(kwargs.keys())
            _validate_columns(cols)
            sets = ", ".join(f"{k} = ?" for k in cols)
            with self._conn() as conn:
                conn.execute(
                    f"UPDATE {table} SET {sets} WHERE id = ?",
                    [*kwargs.values(), row_id],
                )
        self._retry_on_lock(_do_update)

    # ── Trades ──────────────────────────────────────────────

    def insert_trade(self, **kwargs) -> int:
        """Insert a new trade record. Returns the new row ID."""
        kwargs.setdefault("bot_version", __version__)
        return self._insert("trades", **kwargs)

    def update_trade(self, trade_id: int, **kwargs) -> None:
        """Update fields on an existing trade by its ID."""
        self._update("trades", trade_id, **kwargs)

    def get_open_trades(self) -> list[dict]:
        """Fetch all trades with status 'pending' or 'open'.

        Returns a list of plain Python dictionaries (not sqlite3.Row objects)
        so the data can be easily serialized and passed around.

        PYTHON PATTERN — list comprehension with dict():
            `[dict(r) for r in rows]` converts each sqlite3.Row object
            to a regular dictionary.  This is necessary because Row objects
            are tied to the database connection and may not work after
            the connection is closed.
        """
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM trades WHERE status IN ('pending', 'open')"
            ).fetchall()
            return [dict(r) for r in rows]

    def get_all_trades(self) -> list[dict]:
        """Fetch all trades, ordered by creation date (newest first)."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM trades ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    def get_trades_closed_on(self, date: str) -> list[dict]:
        """Fetch trades closed on a specific date (YYYY-MM-DD)."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM trades WHERE status = 'closed' AND exit_time LIKE ?",
                (f"{date}%",),
            ).fetchall()
            return [dict(r) for r in rows]

    # ── Day Trades ──────────────────────────────────────────

    def record_day_trade(
        self, symbol: str, trade_date: str,
        buy_order_id: str = "", sell_order_id: str = "",
    ) -> None:
        """Record a day trade for PDT tracking.

        See risk/pdt_manager.py for how this data is used to enforce
        the Pattern Day Trade rule.
        """
        self._insert(
            "day_trades",
            symbol=symbol, trade_date=trade_date,
            buy_order_id=buy_order_id, sell_order_id=sell_order_id,
        )

    def get_day_trades_since(self, since_date: str) -> list[dict]:
        """Fetch all day trades on or after the given date (ISO format string).

        Used by PDTManager to count trades in the rolling 5-day window.
        """
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM day_trades WHERE trade_date >= ?", (since_date,)
            ).fetchall()
            return [dict(r) for r in rows]

    # ── Daily Snapshots ─────────────────────────────────────

    def save_snapshot(self, **kwargs) -> None:
        """Save or update a daily equity snapshot.

        Uses _upsert (INSERT OR REPLACE) because the `date` column has
        a UNIQUE constraint — running the bot twice on the same day
        just overwrites the previous snapshot.
        """
        self._upsert("daily_snapshots", **kwargs)

    def get_snapshots(self, limit: int = 90) -> list[dict]:
        """Fetch the most recent daily snapshots (newest first).

        Used by PerformanceTracker to calculate max drawdown and
        equity curves.

        Args:
            limit: Maximum number of snapshots to return (default 90 days).
        """
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM daily_snapshots ORDER BY date DESC LIMIT ?", (limit,)
            ).fetchall()
            return [dict(r) for r in rows]

    # ── Signals ─────────────────────────────────────────────

    def log_signal(self, **kwargs) -> int:
        """Record a generated signal for audit trail purposes.

        Every signal the strategies produce is logged here, whether or
        not it was actually acted upon.  The `action_taken` field records
        the outcome (e.g., "executed", "rejected_pdt", "rejected_risk").

        Returns the new signal row ID.
        """
        return self._insert("signals", **kwargs)

    def update_signal_action(self, symbol: str, strategy: str, action: str) -> None:
        """Update action_taken on the most recent signal for a symbol+strategy."""
        def _do_update():
            with self._conn() as conn:
                conn.execute(
                    "UPDATE signals SET action_taken = ? "
                    "WHERE id = (SELECT id FROM signals WHERE symbol = ? AND strategy = ? "
                    "ORDER BY timestamp DESC LIMIT 1)",
                    (action, symbol, strategy),
                )
        self._retry_on_lock(_do_update)

    # ── Options Trades ─────────────────────────────────────

    def insert_options_trade(self, **kwargs) -> int:
        """Insert an options trade record. Returns the new row ID."""
        kwargs.setdefault("bot_version", __version__)
        return self._insert("options_trades", **kwargs)

    def update_options_trade(self, trade_id: int, **kwargs) -> None:
        """Update fields on an existing options trade."""
        self._update("options_trades", trade_id, **kwargs)

    def get_open_options_trades(self) -> list[dict]:
        """Fetch all options trades with status 'open'."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM options_trades WHERE status = 'open'"
            ).fetchall()
            return [dict(r) for r in rows]

    def get_all_options_trades(self) -> list[dict]:
        """Fetch all options trades (newest first)."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM options_trades ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    # ── Scanner ─────────────────────────────────────────────

    def log_scanner_results(self, results: list[dict]) -> None:
        """Persist pre-market scanner results.

        Each result dict should contain: date, symbol, price, gap_pct,
        relative_volume, adr_pct, score, selected.

        Args:
            results: List of candidate dictionaries from the screener.
        """
        for r in results:
            self._insert("scanner_results", **r)
